### ISSUE TITLE
O texto introdutório não detalha o funcionamento do débito do saldo

### ISSUE THREAD

**Issue by hugolinhareso** [hugolinhareso/ticket-machine#25]
Tipo de defeito: Omissão

Gravidade do defeito: Grave

Descrição:
O texto introdutório não detalha o funcionamento do débito do saldo. Devido a isso, nos casos de uso não se observa uma explicação referente ao saldo do cliente/individual.

![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/50311a57-e4a9-470e-8a06-efca8f1b04e6)

**Comment by akajhon** [comment]
Issue resolved.

Actual text:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/feaa65fa-e191-4bbe-b708-4a7972bf59c2)

Link: https://github.com/hugolinhareso/ticket-machine/wiki/Engenharia-de-Requisitos
