### ISSUE TITLE
Informa o saldo total da máquina ou do cliente?

### ISSUE THREAD

**Issue by hugolinhareso** [hugolinhareso/ticket-machine#26]
Tipo de defeito: Ambiguidade

Gravidade do defeito: Grave

Descrição:
O sistema informa o saldo atual do cliente ou o saldo atual do total coletado pela máquina (inclusive de outros clientes que podem ter usado a máquina anteriormente)?

É uma descrição que possibilita mais de uma interpretação, o que pode ocasionar possíveis falhas.

![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/d50fae30-977e-491e-9b58-0f530ddc92a8)

**Comment by akajhon** [comment]
Issue Resolved.

Evidence:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/35d17f3d-13b4-47f4-859a-87c332418ee0)

Link: https://github.com/hugolinhareso/ticket-machine/wiki/Especifica%C3%A7%C3%A3o-CSU001-%7C-Inserir-Dinheiro
