### ISSUE TITLE
Débito do saldo do cliente ou da máquina?

### ISSUE THREAD

**Issue by hugolinhareso** [hugolinhareso/ticket-machine#27]
Tipo de defeito: Ambiguidade

Gravidade do defeito: Grave

Descrição:
O sistema não informa  se o saldo a ser debitado será o do cliente ou o saldo do total coletado pela máquina.

É uma descrição que possibilita mais de uma interpretação, o que pode ocasionar possíveis falhas.

![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/3cd80bd2-fcf3-4edf-ae3f-8c4765af7e65)

**Comment by akajhon** [comment]
Issue Resolved.

Evidence:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/0b5d629a-88dc-4ada-8aef-f1467019f86f)

Link: https://github.com/hugolinhareso/ticket-machine/wiki/Especifica%C3%A7%C3%A3o-CSU002-%7C-Solicitar-Bilhete
