### ISSUE TITLE
Não está especificado que o saldo será descontado após a emissão do bilhete

### ISSUE THREAD

**Issue by hugolinhareso** [hugolinhareso/ticket-machine#28]
Tipo de defeito: Omissão

Gravidade do defeito: Grave

Descrição:
Apesar de estar descrito que o sistema verifica o saldo, não está descrito a ação de que o valor do bilhete será descontado do saldo, apesar de que isso está descrito como pós condição.

![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/3005f432-8a23-4024-88d5-39ab7c8eb9d0)

**Comment by akajhon** [comment]
Issue Resolved.

Evidence:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/601f9513-ae4a-49d4-b20f-be53b27295b5)

Link: https://github.com/hugolinhareso/ticket-machine/wiki/Especifica%C3%A7%C3%A3o-CSU002-%7C-Solicitar-Bilhete
