### ISSUE TITLE
Construtor da classe TicketMachine está recebendo o parametro "valor" ao invés de "precoDoBilhete"

### ISSUE THREAD

**Issue by hugolinhareso** [hugolinhareso/ticket-machine#3]
Código:

![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/4b20c3ba-2c61-42c9-a034-330881c3f584)

Requisitos:

![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/1510d3ce-4ef3-486c-a8dc-4200553a9e26)

**Comment by akajhon** [comment]
Fixed on PR #19
