### ISSUE TITLE
Método getTroco da classe TicketMachine não está usando o TrocoIterator, ao invés disso está usando um Iterator de Integer comum.

### ISSUE THREAD

**Issue by akajhon** [hugolinhareso/ticket-machine#5]
Código com defeito:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/9065eb47-0317-41b3-84eb-45e17add16a6)

Requisito:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/7eb03d34-d26f-4d34-bd75-611494171908)

**Comment by hugolinhareso** [comment]
Issue resolved on #13
