### ISSUE TITLE
O método getTroco() está retornando null, o que significa que a máquina não está fornecendo o troco.

### ISSUE THREAD

**Issue by hugolinhareso** [hugolinhareso/ticket-machine#6]
Código:
![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/73d864c0-fcb1-4575-8ae7-9947e554fe3c)

Requisitos:
![image](https://github.com/hugolinhareso/ticket-machine/assets/72151253/376102e0-8859-4117-9c94-478cf61e631f)

**Comment by akajhon** [comment]
Fixed on PR #21
