### ISSUE TITLE
Existe um método a mais na classe "TrocoIterator": remove()

### ISSUE THREAD

**Issue by akajhon** [hugolinhareso/ticket-machine#7]
Codigo:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/736b7782-2bea-47a1-a7ec-860a3c564659)

Requisito:

![image](https://github.com/hugolinhareso/ticket-machine/assets/69048604/120c3f3f-0c47-4c87-83b8-b9c41867bb87)

**Comment by hugolinhareso** [comment]
Issue resolved on #16
